#!/bin/bash
set -e

echo "$(date "+%Y-%m-%d %H:%M:%S") - Starting archlive setup..."

# Creating archlive directory
comm -23 <(pacman -Qqe | sort) <(pacman -Qqm | sort) > etc/skel/pacman_packages.x86_64
pacman -Qqe > etc/skel/packages.x86_64

# Copying archiso releng config
cp -r /usr/share/archiso/configs/releng/ archlive

# Removing and copying necessary files to archlive
rm -rf etc/mePkg
cp -r etc/* archlive/airootfs/etc/

# Removing autologin configuration
rm -f archlive/airootfs/etc/systemd/system/getty@tty1.service.d/autologin.conf

# Configuring sudoers for wheel group
echo "%wheel ALL=(ALL) NOPASSWD: ALL" > archlive/airootfs/etc/sudoers

# Customizing profiledef.sh
sed -i 's/"archlinux/"cstm-archlinux/' archlive/profiledef.sh
sed -i '/\["\/etc\/shadow"\]="0:0:400"/a \  ["\/etc\/gshadow"]="0:0:400"' archlive/profiledef.sh
sed -i 's/%ARCHISO_UUID%/%ARCHISO_UUID% copytoram=no/' archlive/efiboot/loader/entries/01-archiso-x86_64-linux.conf
sed -i 's/on/off/' archlive/efiboot/loader/loader.conf

# Adding packages to archlive system
cat packages_live.x86_64 >> archlive/packages.x86_64

echo "$(date "+%Y-%m-%d %H:%M:%S") - Archlive setup completed."
