#!/bin/bash
set -e

# Enable logging to a file by uncommenting the following line
exec > >(tee -a build.log) 2>&1

echo "$(date "+%Y-%m-%d %H:%M:%S") - Starting ISO build..."

# Building the ISO
sudo mkarchiso -v archlive

echo "$(date "+%Y-%m-%d %H:%M:%S") - ISO build completed."
